name: Build and test

# Trigger the workflow on push or pull request events
on:
  push:
    branches:
      - main
      - testing
  pull_request:
    branches:
      - main
      - testing

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev libproj22 libproj-dev netcdf-bin libnetcdff-dev

      - name: Build configure script
        run: autoreconf -fi

      - name: Run configure script
        run: ./configure

      - name: Build kestrel
        run: make

      - name: Run tests
        run: make check

      - name: Save logs
        if: ${{ always() }} # run regardless of whether build/test succeeded
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: tests/*.log
          retention-days: 30
